package no.krazyglitch.aoc2025.day7;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class TachyonicTest {
    private static final List<String> DATA = Arrays.stream(("""
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ..............."""
            ).split("\n"))
            .toList();

    @Test
    void testDaySevenPartOne() {
        final int result = Tachyonic.getSplitCount(DATA);
        assertEquals(21, result);
    }

    @Test
    void testDaySevenPartTwo() {
        final long result = Tachyonic.getTimelineCount(DATA);
        assertEquals(40, result);
    }
}